[32m2025-09-15 17:06:12 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ef4eccd5-6b01-48d0-b01a-d0f6e272b2b6 - 91579 - LOGS_CAPTURED - Started capturing logs in process (pid: 91579).
[32m2025-09-15 17:06:12 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ef4eccd5-6b01-48d0-b01a-d0f6e272b2b6 - 91579 - nfl_games - STEP_START - Started execution of step "nfl_games".
[32m2025-09-15 17:06:12 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - ef4eccd5-6b01-48d0-b01a-d0f6e272b2b6 - nfl_games - Loading NFL games data for seasons: [2020, 2021, 2022, 2023, 2024]
[32m2025-09-15 17:06:13 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - ef4eccd5-6b01-48d0-b01a-d0f6e272b2b6 - nfl_games - Loaded 1408 games
[32m2025-09-15 17:06:14 -0600[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - ef4eccd5-6b01-48d0-b01a-d0f6e272b2b6 - 91579 - nfl_games - STEP_FAILURE - Execution of step "nfl_games" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "nfl_games"::

google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/nfl-analytics-472221/jobs?uploadType=multipart: Schema update options should only be specified with WRITE_APPEND disposition, or with WRITE_TRUNCATE disposition on a table partition.

Stack Trace:
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
        fn, context, kwargs, context_arg_provided, config_arg_class, resource_arg_mapping
    )
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewdwyer/Documents/nfl_v2/pipeline/assets/nfl_games.py", line 15, in nfl_games
    store_dataframe_in_bigquery(context, games, "games")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewdwyer/Documents/nfl_v2/pipeline/utils/bigquery_client.py", line 25, in store_dataframe_in_bigquery
    job = client.load_table_from_dataframe(df, table_id, job_config=job_config)
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/cloud/bigquery/client.py", line 2922, in load_table_from_dataframe
    return self.load_table_from_file(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        tmpfile,
        ^^^^^^^^
    ...<9 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/cloud/bigquery/client.py", line 2686, in load_table_from_file
    raise exceptions.from_http_response(exc.response)

The above exception occurred during handling of the following exception:
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

Stack Trace:
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/cloud/bigquery/client.py", line 2682, in load_table_from_file
    response = self._do_multipart_upload(
        file_obj, job_resource, size, num_retries, timeout, project=project
    )
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/cloud/bigquery/client.py", line 3246, in _do_multipart_upload
    response = upload.transmit(
        self._http, data, metadata, _GENERIC_CONTENT_TYPE, timeout=timeout
    )
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        retriable_request, self._get_status_code, self._retry_strategy
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewdwyer/Documents/nfl_v2/.venv/lib/python3.13/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
    ...<5 lines>...
    )
[0m
